GET http://localhost:5078/api/todo/

###

POST http://localhost:5078/api/todo/
content-type: application/json

{
  "Name": "Write unit 45taests",
  "IsCompleted": false,
  "DueDate": "2024-12-05T00:00:00"
}

###

PUT http://localhost:5078/api/todo/3
Content-Type: application/json

{
  "id": 3,
  "name": "Updated Task Name",
  "isCompleted": true,
  "dueDate": "2024-12-10T00:00:00"
}
